version: "3.8"

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    networks:
      - mediline-net

  backend:
    build:
      context: ../backend/MediLine    # path to the Dockerfile above
    container_name: mediline-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    networks:
      - mediline-net

networks:
  mediline-net:
    driver : bridge
    external: true

